name: Update Dependencies
on:
  schedule:
    - cron: "13 21 8 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: update package.json dependencies
        run: |
          npx npm-check-updates -u
          npm update

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update dependencies"
          title: "Update dependencies"
          branch: "update-dependencies"
          delete-branch: true
          reviewers: takkyuuplayer
          body: |
            Run

            ```
            $ git fetch --all
            $ git checkout update-dependencies
            $ git reset --hard origin/update-dependencies
            $ npx cdktf-cli diff
            ```
